CC ?= gcc
CP  = g++

all: face_dpu_multithread reg_rw dma_to_device dma_from_device performance #generate

face_dpu_multithread: face_dpu_multithread.o
	$(CP) -o $@ $^ -lopencv_core -lopencv_imgproc -lopencv_highgui -lpthread 

dma_to_device: dma_to_device.o
	$(CC) -lrt -o $@ $< -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGE_FILE_SOURCE

dma_from_device: dma_from_device.o
	$(CC) -lrt -o $@ $< -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGE_FILE_SOURCE

performance: performance.o
	$(CC) -o $@ $< -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGE_FILE_SOURCE

reg_rw: reg_rw.o
	$(CC) -o $@ $< -g

%.o: %.c
	$(CC) -c -std=c99 -o $@ $< -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGE_FILE_SOURCE -g 

%.o: %.cpp
	$(CP) -o $@ -c $< 

clean:
	rm -rf reg_rw *.o *.bin dma_to_device dma_from_device performance face_dpu_multithread

clear:
	rm -rf *.o *.bin 
